tap 'alerque/tap'
tap 'blackfireio/blackfire'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'gapple/services'
tap 'homebrew/apache'
tap 'homebrew/binary'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/versions'
tap 'homebrew/x11'
tap 'komagata/mycask'
tap 'motemen/ghq'
tap 'neovim/neovim'
tap 'peco/peco'
tap 'sanemat/font'
cask 'java'
cask 'xquartz'
brew 'libyaml'
brew 'pkg-config'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'ansible'
brew 'apr'
brew 'sphinx-doc'
brew 'cmake'
brew 'mysql'
brew 'unixodbc'
brew 'freetds'
brew 'readline'
brew 'icu4c'
brew 'sqlite', args: ['universal']
brew 'apr-util'
brew 'xz', args: ['universal']
brew 'aria2'
brew 'intltool'
brew 'gettext'
brew 'libffi'
brew 'glib'
brew 'd-bus'
brew 'libpng', args: ['universal']
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'pixman'
brew 'cairo'
brew 'pcre'
brew 'git', args: ['with-blk-sha1', 'with-brewed-curl', 'with-brewed-openssl', 'with-gettext', 'with-pcre', 'with-persistent-https']
brew 'gobject-introspection'
brew 'at-spi2-core'
brew 'atk'
brew 'at-spi2-atk'
brew 'autoconf'
brew 'automake'
brew 'avro-tools'
brew 'aws-elasticbeanstalk'
brew 'awscli'
brew 'node'
brew 'azure-cli'
brew 'bash'
brew 'bats'
brew 'bdw-gc'
brew 'bfg'
brew 'binutils'
brew 'bison'
brew 'boost'
brew 'popt'
brew 'librsync'
# brew 'burp'
brew 'c-ares'
brew 'cabextract'
brew 'ccache'
brew 'chromedriver'
brew 'gmp'
brew 'isl'
brew 'cloog'
brew 'cocot'
brew 'colordiff'
brew 'colortail'
brew 'go'
brew 'corectl'
brew 'coreutils'
brew 'cowsay'
brew 'cpanminus'
brew 'cscope'
brew 'ctags'
brew 'curl'
brew 'libsodium'
brew 'zeromq'
brew 'czmq'
brew 'dnsmasq'
brew 'docbook'
brew 'docker'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'harfbuzz'
brew 'pango'
brew 'graphviz'
brew 'doxygen'
brew 'e2fsprogs'
brew 'libtool', args: ['universal']
brew 'jpeg', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'wxmac'
brew 'erlang'
brew 'elixir'
brew 'libtasn1', args: ['universal']
brew 'nettle'
brew 'gnutls'
brew 'little-cms2', args: ['universal']
brew 'imagemagick'
brew 'emacs', args: ['with-cocoa']
brew 'embulk'
brew 'faac'
brew 'fasd'
brew 'x264'
brew 'lame'
brew 'xvid'
brew 'ffmpeg'
brew 'findutils', args: ['with-default-names']
brew 'fio'
brew 'flex'
brew 'fontforge'
brew 'gawk'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gd', args: ['universal']
brew 'gdbm', args: ['universal']
brew 'python'
brew 'gdb'
brew 'gdk-pixbuf'
brew 'geoip'
brew 'gh'
brew 'gibo'
brew 'gist'
brew 'git-flow'
brew 'libxml2', args: ['with-python']
brew 'gnome-doc-utils'
brew 'jasper', args: ['universal']
brew 'libepoxy'
brew 'gsettings-desktop-schemas'
brew 'hicolor-icon-theme'
brew 'gtk+3'
brew 'gnome-icon-theme'
brew 'gnu-indent', args: ['default-names']
brew 'gnu-sed', args: ['default-names']
brew 'gnu-tar'
brew 'gnu-time'
brew 'gnu-which', args: ['with-default-names']
brew 'goaccess'
brew 'gtk+'
brew 'hadoop'
brew 'html-xml-utils'
brew 'htop-osx'
brew 'httpie'
brew 'hub', args: ['HEAD']
brew 'unar'
brew 'ievms'
brew 'jmeter', args: ['with-plugins']
brew 'oniguruma'
brew 'jq'
brew 'keychain'
brew 'kubernetes-cli'
brew 'ldns'
brew 'lftp'
brew 'libev'
brew 'libevent'
brew 'libgpg-error'
brew 'libgcrypt'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libpcl'
brew 'libsmi'
brew 'libvo-aacenc'
brew 'libxslt'
brew 'lua'
brew 'luajit'
brew 'lv'
brew 'lzip'
brew 'python3'
brew 'macvim', args: ['with-lua', 'with-luajit', 'with-python3', 'with-override-system-vim']
brew 'maven'
brew 'mhash'
brew 'mcrypt'
brew 'md5sha1sum'
brew 'mercurial'
brew 'protobuf'
brew 'mobile-shell'
brew 'nginx', args: ['with-spdy', 'with-gunzip', 'HEAD']
brew 'ngrep'
brew 'ngrok'
brew 'nifi'
brew 'nkf'
brew 'nmap'
brew 'ossp-uuid'
brew 'p7zip'
brew 'parallel'
brew 'peco'
brew 'perl-build'
brew 'pigz'
brew 'plenv'
brew 'portaudio'
brew 'pssh'
brew 'pv'
brew 'qt'
brew 'qt5'
brew 'ruby-build'
brew 'rbenv'
brew 're2c'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rename'
brew 'rmtrash'
brew 's3cmd'
brew 'sane-backends', args: ['universal']
brew 'scala'
brew 'scrollkeeper'
brew 'selenium-server-standalone'
brew 'siege'
brew 'sl'
brew 'spdylay'
brew 'squid'
brew 'ssh-copy-id'
brew 'subversion'
brew 'sysbench'
brew 'the_platinum_searcher'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tomcat', args: ['with-fulldocs']
brew 'tomcat-native', args: ['with-apr']
brew 'trafficserver', args: ['with-spdy', 'HEAD']
brew 'tree'
brew 'unison'
brew 'unrar'
brew 'w3m'
brew 'watch'
brew 'wdiff', args: ['with-gettext']
brew 'weighttp'
brew 'wget'
brew 'wine'
brew 'winetricks'
brew 'wireshark', args: ['with-qt', 'with-qt5', 'with-headers', 'with-libsmi', 'with-lua', 'with-portaudio']
brew 'xhyve'
brew 'z'
brew 'zdelta'
brew 'zenity'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'blackfireio/blackfire/blackfire-agent'
brew 'homebrew/dupes/zlib'
brew 'homebrew/apache/httpd24', args: ['with-mpm-worker']
brew 'homebrew/boneyard/aws-iam-tools'
brew 'homebrew/dupes/diffutils'
brew 'homebrew/dupes/ed', args: ['with-default-names']
brew 'homebrew/dupes/expect', args: ['enable-threads']
brew 'homebrew/dupes/file-formula'
brew 'homebrew/dupes/gpatch'
brew 'homebrew/dupes/grep', args: ['with-default-names']
brew 'homebrew/dupes/gzip'
brew 'homebrew/dupes/less'
brew 'homebrew/dupes/libiconv'
brew 'homebrew/dupes/libpcap'
brew 'homebrew/dupes/m4'
brew 'homebrew/dupes/make'
brew 'homebrew/dupes/ncurses'
brew 'homebrew/dupes/nano'
brew 'homebrew/dupes/openssh', args: ['with-ldns']
brew 'homebrew/dupes/rsync'
brew 'homebrew/dupes/screen'
brew 'homebrew/dupes/unzip'
brew 'homebrew/php/php70'
brew 'homebrew/php/composer'
brew 'homebrew/versions/bison27'
brew 'homebrew/x11/xclip'
brew 'neovim/neovim/neovim', args: ['HEAD']
brew 'sanemat/font/ricty', args: ['disable-fullwidth', 'powerline', 'vim-powerline']
cask 'adobe-air'
cask 'alfred'
cask 'anaconda'
cask 'azure-cli'
cask 'bettertouchtool'
cask 'boot2docker'
cask 'cacoo-ninja'
cask 'chefdk'
cask 'clipmenu'
cask 'cyberduck'
cask 'diffmerge'
cask 'dockertoolbox'
cask 'dropbox'
cask 'elasticwolf'
cask 'filezilla'
cask 'firefox'
cask 'flash'
cask 'freemind'
cask 'github-desktop'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'google-refine'
cask 'gyazo'
cask 'hipchat'
cask 'hyperswitch'
cask 'intellij-idea'
cask 'intellij-idea-ce'
cask 'iterm2-nightly'
cask 'kobito'
cask 'licecap'
cask 'mi'
cask 'mono-mdk'
cask 'mosh'
cask 'mou'
cask 'multifirefox'
cask 'mysqlworkbench'
cask 'nndd'
cask 'onyx'
cask 'opera'
cask 'owncloud'
cask 'packer'
cask 'pandoc'
cask 'real-vnc'
cask 'sequel-pro'
cask 'serf'
cask 'silverlight'
cask 'skype'
cask 'slack'
cask 'soundnode'
cask 'sourcetree'
cask 'stay'
cask 'sts'
cask 'switchresx'
cask 'tableau'
cask 'tableau-public'
cask 'terraform'
cask 'the-unarchiver'
cask 'tigervnc-viewer'
cask 'toggldesktop'
cask 'unity'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vivaldi'
cask 'vnc-viewer'
cask 'vox'
cask 'vox-preferences-pane'
cask 'wireshark'
cask 'xmind'
cask 'xtrafinder'
