[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
# hook_add = '''
# autocmd VimEnter * colorscheme jellybeans
# '''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {'colorscheme': 'seoul256'}
set laststatus=2
if !has('gui_running')
  set t_Co=256
endif
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'gcmt/wildfire.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'
