[[plugins]]
repo = 'Shougo/neocomplete'
if = "has('lua')"
on_i = 1

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
  if !has("python3")
    execute "!/usr/local/bin/pip3 install neovim"
  endif
  let g:deoplete#enable_at_startup = 1
  source ~/.config/nvim/deoplete.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_ft = 'snippet'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet'
on_i = 1

# language-specific

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
on_ft = 'python'

# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
[[plugins]]
repo = 'zchee/deoplete-go'
depends = 'deoplete.nvim'
on_i = 1
on_ft = 'go'

# C/C++
[[plugins]]
repo = 'zchee/deoplete-clang'
depends = 'deoplete.nvim'
on_ft = ['c', 'cpp']

# PowerShell
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = 'ps1'

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
