[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'scrooloose/nerdtree'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_ft = 'snippet'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet'
on_i = 1

# language-specific

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
